### ISSUE TITLE
 Implementar Cadastro de Fazendas com Firebase e Validação de Formulários

### ISSUE THREAD

**Issue by Bela55** [Bela55/SegundaFase#4]
Descrição:
Permitir que os usuários cadastrem informações sobre suas fazendas no aplicativo, utilizando Firebase para armazenamento e validação de formulários.

Tarefas:

> Criar formulário de cadastro de fazendas.
>  Incluir campos relevantes, como nome da fazenda, localização, etc.
>  Validar dados de entrada e salvar no Firebase.
>  Configurar validação de formulários para garantir dados consistentes.

**Comment by Iran55** [comment]
Completed
