### ISSUE TITLE
Implementar Funcionalidade de Contexto na tela HOME

### ISSUE THREAD

**Issue by Bela55** [Bela55/SegundaFase#7]
Aprimorar a eficiência e coesão da Tela HOME através da implementação de um Contexto para gerenciamento de estado.

Tarefas:
Configuração de Contexto:

 

> Criar um Contexto para gerenciamento de estado específico da Tela HOME.
> Garantir que o Contexto seja inicializado e acessível a todos os componentes necessários.

**Comment by Iran55** [comment]
Completed
